// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Rule struct {
	Name  string `json:"name"`
	Value int    `json:"value"`
}

type VerifyResult struct {
	Valid   bool     `json:"valid"`
	NoMatch []string `json:"noMatch"`
}
